### ISSUE TITLE
RE 3, room 110, Nemesis crash in certain situations

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#315]
### Version

3.0.1 (412b94e)

### Seed

R730-5GBZ-ZJLF19N51YB00N92EJM0WC305HEU0ZZZ5XZ

### Scenario

RE 3 (Jill)

### What happened?

Playing as RE3R Jill. First time entering it showed the nemesis cutscene, worked fine. when coming back through exiting the police station side it crashed upon entering the room. The whole area past that room worked totally fine too, only area that maybe caused an issue was 2nd floor RPD where the nearby nemesis music was playing, so maybe there was a conflict with the RPD entrance since it was expecting a different nemesis?

**Comment by IntelOrca** [comment]
Are you able to provide a saved game that crashes when you go into this room?

**Comment by SolidFat** [comment]
Unfortunately I didn't have a save. I was on my way back to use an item I know, I'd searched the entire area past the nemesis room.

**Comment by IntelOrca** [comment]
A common issue with RE 3 is that so much depends on the state and flags of the game. If I can't jump to the room to reproduce the crash from the start room - it makes it difficult to fix. And playing the game for every crash is time consuming, and not necesarily guaranteed to reproduce the issue. That is why it is helpful to have a saved game so that I can jump to the room after loading it in order to get the crash.

**Comment by SolidFat** [comment]
Ah. I see what you mean. I'll start doing more console saves while playing from here on out so I can maybe have something to hand over next time.
