### ISSUE TITLE
RE 3, room 303, softlock when random enemy placement enabled

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#429]
### Version

3.0.4 (ddca0a7)

### Seed

R730-2LB5-ZTHH0HMZ9YF00ZRZZZZ0ZZZZZZZZZZZZF3Z

### Scenario

RE 3 (Jill)

### Player Character

Leon (RE2R)

### What happened?

After using all the train parts then jumping out the window from the live selection, I checked the side door in front of the clocktower and it's locked from the other side.
I go through the main double doors and it takes me to the warehouse saferoom with no where else to go. I also checked the seed log and saw that it should have let me through the door.
Debug save attached.
[01_2023-06-04 22^34.57.zip](https://github.com/IntelOrca/biorand/files/11649017/01_2023-06-04.22.34.57.zip)

**Comment by themitosan** [comment]
I did some few tests yesterday and I wrote a small document with proofs that same thing is happening with me. 
It happens when I create new games with door rand enabled but with *very small segment sizes*.

You can check the full report by using this [link](https://github.com/IntelOrca/biorand/files/11652544/Rand.Results.zip).

**Comment by IntelOrca** [comment]
@themitosan thanks, nice work with the auto map gen btw. I can see that being used as a nice livestream overlay!
