### ISSUE TITLE
RE3 - Crashes while playing as Hunk

### ISSUE THREAD

**Issue by Hynisel** [IntelOrca/biorand#443]
### Version

3.0.6 (d8709f5)

### Seed

Seed: R730-HRLY-TNUH40MZLYE20NK4TK4000000000RZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Hunk

### What happened?

The game crashes when using the fire hook in the restaurant.

If necessary I will open a new bug report but I have noticed other problems while playing as Hunk. 
1) the mine thrower has a different skin from the default one ( I’m not sure if it is intentional). Sometimes after being fired the mines causes a graphic glitch where they are shaped like Hunk’s hand. I’m having difficulty taking screenshots as it causes the game to crash most of the time.
2) I’m still trying to reproduce it but it seems that randomly while playing, Hunk’s walking (not running) gets glitched creating the impression that he “teleport” forward from his current position.
[01_2023-06-16 18^55.zip](https://github.com/IntelOrca/biorand/files/11774699/01_2023-06-16.18.55.zip)

**Comment by TheMitu97** [comment]
Having similar issue with warping animations and crashes, also noticed it on other new characters like Regina. It's so bad that being on caution makes you almost walk in place, which is obviously not ideal.

**Comment by Neil-F2** [comment]
I tested and...
All new character mentioned in the update have this glitchy walking animation, except Rebecca, since she wasn't added as playable (The update says she was added)
Also i have notice this issue happen when you change or unequip your initial weapon, and it continues to happen even when you move to other rooms, if you don't unequip your weapon then this don't happen until you do
I tested some old characters and so far they don't have this problem

**Comment by IntelOrca** [comment]
Fixed by 7a54245
