### ISSUE TITLE
Conversion of sound files can sometimes error

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#519]
### Version

3.1.0

### Seed

R710-004P-XN3300M398000NQ92EK45XWVZZZZZZZZZZULYYZZZZ

### Scenario

RE 1 (Jill)

### Player Character

dont know couldnt get that far

### What happened?

seeds not being able to be generated due to .ogg file issues. including a screenshot as an example. the only way i found to make this stop happening was to turn off the "allow any character voice" option.
![GPizWrK](https://github.com/IntelOrca/biorand/assets/121378553/84ff77a0-cd1a-459e-bed3-589ff3df0412)

**Comment by OnSilverwings** [comment]
I too have this problem with the same template message. Most errors involved Ark although I did have one related to Piers.

The option that triggered the problem was randomizing cutscenes, if I uncheck this, everything runs fine. RE2 and RE3 appear to be fine with the box checked though.
![biorand](https://github.com/IntelOrca/biorand/assets/95526579/20e8814e-56f5-475c-b00d-e7eff171f32d)
