### ISSUE TITLE
square crank does not open the shutter

### ISSUE THREAD

**Issue by MsieurDooM** [IntelOrca/biorand#651]
### Version

3.1.6 (0f27194)

### Seed

R730-81E4-XXHH4HM5Z1Y000QJZZZZGYZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

jill Stars suit

### What happened?

 room 105 As the title say, when I use the crank it just retrun to the game without opening the shutter

**Comment by themitosan** [comment]
**Hello @MsieurDooM, doing fine?**

This happens because RE3 Uptown has two sets of maps: One for late-afternoon and other for night. Since the game **only allows you to get this item at night**,  this location (at this point in the game) **doesn't believe that you already have this item (crank)**. To trigger this time transition, **You must get the lockpick at S.T.A.R.S. Room, Police Station**.

Cheers 💜

**Comment by IntelOrca** [comment]
What @themitosan is correct, unfortunately there is no work around yet.

**Comment by MsieurDooM** [comment]
ok thanks, I take note for future runs (square crank = night crank)
